### ISSUE TITLE
I want to test image for enhance, but haven't the wights/weights.166.hdf5

### ISSUE THREAD

**Issue by CodeCat-Q** [kauziishere/lowLightImageEnhancement#1]
hello,
       Could you provide a trained HDF5 file for test the model performance?
       I run the custom_test.py but get the msg: "unable to open file: name = './weights/weights.166.hdf5'"

       I want to run the model for image preprocessing of my research.
       Thank you!

**Comment by kauziishere** [comment]
Hi man, Sorry Wasn't able to address comment before, I don't have the weights with me right now. Hope you found a solution.
